# Generated by Django 3.2.25 on 2024-07-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
